### PR TITLE
Update install instructions

### PR DESCRIPTION
**Pull request by SteelWagstaff**
Update local installation instructions for MacOS and Windows and add instructions for Ubuntu.

### CODE REVIEW

**Comment by SteelWagstaff** [comment]
@fdalcin and @arzola Can you take a look at Mac docs and suggest any changes, especially to dependencies step? @ho-man-chan can you do the same for Windows? @richard015ar can you be reviewer for Ubuntu?

**Comment by SteelWagstaff** [comment]
Pressbooks devs should now be able to use https://github.com/pressbooks/pressbooksedu-golden-bedrock in place of the generic bedrock to install the full set of plugins/themes used on our client networks.

**Comment by arzola** [comment]
Looks good, I'll try it

**Comment by fdalcin** [comment]
I'll try it as well

**Comment by fdalcin** [comment]
Some considerations related to the MacOS instructions.

* Newer versions of [Homebrew Cask](https://caskroom.github.io) changed the installation syntax. The command changed from `brew cask install app-name` to `brew install app-name --cask`;
* We should instruct to use [Composer](https://getcomposer.org/) v1. Running v2 will cause some issues;
* I was unable to complete the **Unit testing** section (I'll check with you later today);
* The command `npm run build` is invalid since it doesn't exist in `package.json`. The `npm run build:production` one worked well;

Other than that, the setup is working great.

image

**Review by ho-man-chan — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
